### ISSUE TITLE
StatAssist in objectdetection?

### ISSUE THREAD

**Issue by xieydd** [clovaai/StatAssist-GradBoost#1]
I never find StatAssist in `https://github.com/clovaai/StatAssist-GradBoost/blob/master/Object_Detection/qtrainval.py`, can you help me point it? Very thanks.

**Comment by tgisaturday** [comment]
Sorry for the inconvenience. It's from line 185 to 240 which is commented as "fp_warmup". Thanks for pointing this out.

**Comment by xieydd** [comment]
Thanks for your response, i got the fp_warmup is StateAssist from the paper. ：）
