### ISSUE TITLE
Error in Training

### ISSUE THREAD

**Issue by xieydd** [clovaai/StatAssist-GradBoost#2]
When i transfer StatAssist-GradBoost to my face detection task, an error happend in training phase; Below is log:
```
Epoch: [6]  [  0/202]  eta: 0:25:54  lr: 0.001  img/s: 40.46101009839138  loss: 53.6955 (53.6955)  losses: 53.6955 (53.6955)  box losses: 4.2484 (4.2484)  class losses: 3.2239 (3.2239)  landmark losses: 41.9749 (41.9749)  time: 7.6959  data: 6.1140  max mem: 4881
Traceback (most recent call last):
  File "train_quantization_sg.py", line 586, in <module>
    main(args)
  File "train_quantization_sg.py", line 419, in main
    args.print_freq, priors)
  File "train_quantization_sg.py", line 100, in train_one_epoch
    output = model(image)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt1/FaceDetect-QAT/models/qat_slim.py", line 29, in forward
    x)
  File "/opt1/FaceDetect-QAT/models/net_slim.py", line 131, in _forward_impl
    x1 = self.conv1(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/intrinsic/qat/modules/conv_fused.py", line 243, in forward
    return self.activation_post_process(F.relu(ConvBn2d._forward(self, input)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/intrinsic/qat/modules/conv_fused.py", line 95, in _forward
    conv = self._conv_forward(input, self.weight_fake_quant(scaled_weight))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/quantization/fake_quantize.py", line 81, in forward
    _scale, _zero_point = self.calculate_qparams()
  File "/opt/conda/lib/python3.7/site-packages/torch/quantization/fake_quantize.py", line 76, in calculate_qparams
    return self.activation_post_process.calculate_qparams()
  File "/opt/conda/lib/python3.7/site-packages/torch/quantization/observer.py", line 510, in calculate_qparams
    return self._calculate_per_channel_qparams(self.min_vals, self.max_vals)
  File "/opt/conda/lib/python3.7/site-packages/torch/quantization/observer.py", line 148, in _calculate_per_channel_qparams
    assert (torch.sum(diff) == len(diff)), "min_vals should be less than max_vals for indices."
AssertionError: min_vals should be less than max_vals for indices.
```
In addation, it can train a few epoch.

**Comment by tgisaturday** [comment]
It seems to be typical pytorch QAT error we also encountered during our research. Our heuristic solutions were:
1. Lowering initial learning rate.
2. Using qnnpack instead of fbgemm.
3. Increasing batch size.
4. Using torch1.5 or above.

We strongly recommend 0.1 * lr of FP version since QAT min max observers are quite vulnerable to high learning rates... using GradBoost optimizers mitigates this issue. (0.1 * lr  -> 0.5 * lr)

Feel free to ask if you have more questions!

**Comment by xieydd** [comment]
Thanks for your detailed response. Thanks for your detailed response. When i change lr from 1e-3 to 1e-4, it still happend. And i notice, this error happend after evaluate phase. And i delete evaluate phase and use lr 1e-3, it works well so far. I will continue to pay attention to the situation.
I use pytorch 1.5.1, batch_size=64, qat backend fbgemm.
```
Saving models after epoch  79
Starting training for epoch 80
Epoch: [80]  [  0/202]  eta: 0:19:26  lr: 0.001  img/s: 54.834167142452976  loss: 16.8163 (16.8163)  losses: 16.8163 (16.8163)  box losses: 1.4175 (1.4175)  class losses: 1.9719 (1.9719)  landmark losses: 12.0094 (12.0094)  time: 5.7742  data: 4.6069  max mem: 4987
Epoch: [80]  [ 10/202]  eta: 0:04:05  lr: 0.001  img/s: 79.40996368746072  loss: 19.4886 (19.2206)  losses: 19.4886 (19.2206)  box losses: 1.5180 (1.5527)  class losses: 2.0612 (2.0896)  landmark losses: 14.0161 (14.0257)  time: 1.2787  data: 0.4191  max mem: 4987
Epoch: [80]  [ 20/202]  eta: 0:03:10  lr: 0.001  img/s: 80.0381222149503  loss: 19.1006 (19.0707)  losses: 19.1006 (19.0707)  box losses: 1.5324 (1.5513)  class losses: 2.0612 (2.0671)  landmark losses: 13.9015 (13.9009)  time: 0.8089  data: 0.0003  max mem: 4987
Epoch: [80]  [ 30/202]  eta: 0:02:46  lr: 0.001  img/s: 83.67336661331272  loss: 18.7427 (19.0069)  losses: 18.7427 (19.0069)  box losses: 1.5274 (1.5253)  class losses: 2.0083 (2.0448)  landmark losses: 13.7788 (13.9114)  time: 0.7969  data: 0.0003  max mem: 4987
Epoch: [80]  [ 40/202]  eta: 0:02:31  lr: 0.001  img/s: 79.81233377723824  loss: 18.5289 (18.8371)  losses: 18.5289 (18.8371)  box losses: 1.4448 (1.5146)  class losses: 1.9738 (2.0248)  landmark losses: 13.5451 (13.7831)  time: 0.8156  data: 0.0004  max mem: 4987
Epoch: [80]  [ 50/202]  eta: 0:02:17  lr: 0.001  img/s: 81.08235356660863  loss: 18.5289 (18.9411)  losses: 18.5289 (18.9411)  box losses: 1.4404 (1.5160)  class losses: 1.9738 (2.0279)  landmark losses: 13.6984 (13.8812)  time: 0.8142  data: 0.0003  max mem: 4987
Epoch: [80]  [ 60/202]  eta: 0:02:06  lr: 0.001  img/s: 77.39699500590059  loss: 18.6170 (18.9340)  losses: 18.6170 (18.9340)  box losses: 1.4276 (1.5078)  class losses: 1.9650 (2.0217)  landmark losses: 13.8543 (13.8967)  time: 0.8046  data: 0.0003  max mem: 4987
Epoch: [80]  [ 70/202]  eta: 0:01:56  lr: 0.001  img/s: 79.32977440693755  loss: 18.7085 (18.9166)  losses: 18.7085 (18.9166)  box losses: 1.4443 (1.5082)  class losses: 1.9599 (2.0171)  landmark losses: 13.8554 (13.8831)  time: 0.8115  data: 0.0003  max mem: 4987

```

**Comment by yjyoo3312** [comment]
@xieydd Thank you for having an interest in our work! 
- fbgemm backend is not well supported by PyQAT and we recommend you to use qnnpack (PyQAT team seems to concentrate on qnnpack than fbgemm). 
- Also, it would be safe to evaluate the model (in training phase) by defining a new model and copy the trained weight to the new model, as can be seen in [here](https://github.com/clovaai/StatAssist-GradBoost/blob/b161508f55b71279544fd757a206c9f59703593a/Object_Detection/qeval_convert.py#L406). It is because the min, max, and zero statistics are updated in evaluation phase as well. Also, as we and you expected, evaluating the model during the training phase using **the same model** is prone to bug, currently.
- Lastly, we recommend you to [check](https://github.com/clovaai/StatAssist-GradBoost/blob/master/Object_Detection/qtdsod.py) if your model is well converted or not because training process doesn't notice error messege although it has a problem in really converting the model (They just fakeQuantized the model in training).
- Since the current QAT library requires a very strict coding style, it would be a good option to refer to the coding style of our detector example.

**Comment by tgisaturday** [comment]
@xieydd Regarding evaluation phase, we also had same issue when we were training segmentation models with multi-gpu. If you are using multi-gpu, it can be another cause. Seems that pytorch QAT has some unknown bugs with multi-gpu support.

**Comment by xieydd** [comment]
@yjyoo3312 Thanks for your detailed response. 
- I already change fbgemm to qnnpack, i will compare two backend for my task.Because use normal optimizer and policy, fbgemm will get better.
- Maybe there are some bug in my evaluate phase, i wil check and fix it.
- I tested QAT model, the model is well converted and test
- If it's convenient for you, i can pr my facedetect qat code. It is difficult for one to detect mistakes without code review. :  )

**Comment by yjyoo3312** [comment]
> @yjyoo3312 Thanks for your detailed response.
> 
> * I already change fbgemm to qnnpack, i will compare two backend for my task.Because use normal optimizer and policy, fbgemm will get better.
> * Maybe there are some bug in my evaluate phase, i wil check and fix it.
> * I tested QAT model, the model is well converted and test
> * If it's convenient for you, i can pr my facedetect qat code. It is difficult for one to detect mistakes without code review. :  )

Sure! we can see the code together :)

**Comment by xieydd** [comment]
@yjyoo3312 I have invited you to my [private repo](https://github.com/xieydd/QAT), because the repo is not ready open :  ）
Thanks again. Below is my test result
| Plan | Hard | Medium | Easy| WiderFace Speed
| ---- | ---- | ----  | ---- | ---- |
| FaceDetect| 0.31| 0.64| 0.78| |
| FaceDetect-QAT| 0.294| 0.612| 0.749| |
| FaceDetect-QAT-StatAssist-GradBoost-fbgemm| 0.31| 0.64| 0.759 | 0.076s|
| FaceDetect-QAT-StatAssist-GradBoost-qnnpack| 0.307| 0.634| 0.766 | 0.058s|

**Comment by xieydd** [comment]
@yjyoo3312 One Question has nothing to do with the issue. Have you compare the tf2 qat with pytorch qat. ：）

**Comment by yjyoo3312** [comment]
> @yjyoo3312 One Question has nothing to do with the issue. Have you compare the tf2 qat with pytorch qat. ：）

In this stage, we have not tested tf2 qat yet but we have plan to do so.

**Comment by xieydd** [comment]
@yjyoo3312 
1. Is there anything that needs to be improved or bug ：）
2. We can work together for tf qat ：）

**Comment by yjyoo3312** [comment]
@xieydd 
1. Yepp:) Thank you for sharing a chance to read the good code. I read the code, and it seems that the accuracy is nice considering that the model uses 300x300 as input. One thing I optionally curious about is the mAP when using FPN + equivalent anchor setting as RetinaFace (For quantitative comparison). 
2. Sure, I will love to:)

**Comment by xieydd** [comment]
> @xieydd
> 
> 1. Yepp:) Thank you for sharing a chance to read the good code. I read the code, and it seems that the accuracy is nice considering that the model uses 300x300 as input. One thing I optionally curious about is the mAP when using FPN + equivalent anchor setting as RetinaFace (For quantitative comparison).
> 2. Sure, I will love to:)

1. Clear one point, i use 320 as long_side :  ）. and This model not use FPN, althogh it has FPN code .
2. tf qat, have a plan?
